name: Continuous Integration
on: [push] # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v4 # Adds a step to checkout the repository code

      - name: Hello world # Name of step
        run: echo 'Hello world' # Command to run

      - name: Build the C# code
        run: dotnet build

      - name: Run the tests
        run: dotnet test
